# Supabase project settings
# Find these in Supabase dashboard: Project Settings -> API
supabase.url=https://gtdnhebxyfubvkrniczr.supabase.co
supabase.anonKey=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0ZG5oZWJ4eWZ1YnZrcm5pY3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxMjg3NjgsImV4cCI6MjEwNDcwNDc2OH0.kChJ4x8exlkRfJV5Khqc3v-Qc3hx4nIDmlG7V76JNEI
